Did what i could
TheBarbossa/-c-sharp-syllabus- pull request #11
Opened 2021-08-18 19:23 UTC by TheBarbossa

2021-08-20 18:41 UTC, ausmoons requested changes

2021-08-20 18:41 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/EnergyDrinks/Program.cs
> +        static double preferCitrus()
Ar lielo burtu

2021-08-20 18:41 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise1/Product.cs
> +        private string Name
Private neiet kopā ar { get; set; } un ja ietu, tad tas būtu vienā rindā public double PriceAtStart { get; set; }

2021-08-20 18:41 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise4/Movie.cs
> +        private string Title;
deklarē pašā augšā visu un _title. Kā arī deklarē pirms izmanto

2021-08-20 18:41 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise5/Date.cs
> +        public int month;
Vai tad šiem nav jābū private?

2021-08-20 18:41 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise7/Dog.cs
> +        public Dog (string name,string sex) {
{ jaunā rindā

2021-08-20 18:41 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise7/DogTest.cs
> +            d8.fathersName();
fathersName bija jābūt ar lielo burtu

2021-08-20 18:41 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise9/SwapPointsTest.cs
> +        public static void swapPoints(Object obj, Object obj2)
Ar lielo burtu un pirms metodēm ir jāliek tukša rinda. Un vispā tu izmano Point, kāpēc liec object un tad casto?

2021-08-22 18:31 UTC, ausmoons requested changes

2021-08-22 18:31 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise4/Movie.cs
> +        private string Title;
_title

2021-08-22 18:31 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise4/Movie.cs
>          public void getPG()
Ar lielo burtu

2021-08-22 18:31 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise5/Date.cs
> +        private int Year { get; set; }
Faila sākumā, bez get;set

2021-08-22 18:32 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise9/SwapPointsTest.cs
> +        public static void swapPoints(Object obj, Object obj2)
Commitam ir jābūt paskaidrojošam. Varēji vismaz ierakstīt PR comment fixes (bet darbā parasti saka, lai raksta galvenās metodes, kas labotas)

2021-08-23 09:22 UTC, TheBarbossa commented
Es pamainīju nosaukumus, kur vajadzēja un noņēmu liekos {get;set;}

2021-08-23 15:50 UTC, ausmoons approved these changes

2021-08-23 19:38 UTC, merged