Pretty much done
TheBarbossa/-c-sharp-syllabus- pull request #12
Opened 2021-08-24 18:42 UTC by TheBarbossa

2021-08-24 18:49 UTC, ausmoons requested changes

2021-08-24 18:49 UTC, ausmoons commented on csharp-basics/exercises/Collections/Exercise1/Program.cs
> +            };
Šo ir grūti pārskatī. Saliec tukšas rindas pēc }

2021-08-24 18:49 UTC, ausmoons commented on csharp-basics/exercises/Collections/FlightPlanner/Program.cs
> +        private const string Path = "C:\\Users\\SB00366\\OneDrive - Riga Technical University\\Desktop\\Codelex\\-c-sharp-syllabus-\\csharp-basics\\exercises\\Collections\\FlightPlanner/flights.txt";
../../.., lai var reusot

2021-08-24 18:49 UTC, ausmoons commented on csharp-basics/exercises/Collections/FlightPlanner/Program.cs
> +                    dictionary.Add(title, new List<string>());
Ieliec {}. Te ir daudz koda, nav viegli uztverams

2021-08-24 18:49 UTC, ausmoons commented on csharp-basics/exercises/Collections/FlightPlanner/Program.cs
> +
Lieka tukša rinda. Pārskati visus failus

2021-08-24 18:49 UTC, ausmoons commented on csharp-basics/exercises/Collections/FlightPlanner/Program.cs
> +                                    Console.WriteLine(listMember);
Visur saliec {}

2021-08-24 20:12 UTC, TheBarbossa commented
Saliku iekavas un dažas atstarpes 1.uzd..

2021-08-25 17:11 UTC, ausmoons requested changes

2021-08-25 17:11 UTC, ausmoons commented on csharp-basics/exercises/Collections/FlightPlanner/Program.cs
> +        private const string Path = "C:/Users/SB00366/OneDrive - Riga Technical University/Desktop/Codelex/-c-sharp-syllabus-/csharp-basics/exercises/Collections/FlightPlanner/flights.txt";
vai citiem šis path uz sava datora derēs? Nē. Saliec ar ../../

2021-08-25 17:11 UTC, ausmoons commented on csharp-basics/exercises/Collections/Histogram/Program.cs
> +        private const string Path = "C:/Users/SB00366/OneDrive - Riga Technical University/Desktop/Codelex/-c-sharp-syllabus-/csharp-basics/exercises/Collections/Histogram/midtermscores.txt";
Nomaini

2021-08-27 07:51 UTC, TheBarbossa commented
Nomainīju abus path uz iepriekšējiem.

2021-08-29 18:03 UTC, ausmoons approved these changes

2021-08-29 18:28 UTC, merged